# Generated by Django 5.1.3 on 2024-11-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupe',
            table='Groupe',
        ),
        migrations.AlterModelTable(
            name='role',
            table='Role',
        ),
    ]
